# Don't change this! Version used to track needed updates.
version = 1
slotMode = "DEFAULT_SLOT"
hideDebugInfoInSurvival = false
cancelElytraFlyingInLiquid = true
preventElytraRightClickEquip = false

[accessorySettings]
clockAccessory = true
compassAccessory = true
recoveryCompassAccessory = true
calendarAccessory = true
elytraAccessory = true
spyglassAccessory = false
lanternAccessory = true
totemOfUndyingAccessory = true
enderChestAccessory = false
shulkerBoxAccessory = false
arrowAccessory = false

[infoOverlaySettings]
showYCoordinate = true
obfuscateCompassIfNotOverworld = false
obfuscateClockIfNotOverworld = true
useObfuscationEffect = true

[infoOverlaySettings.overlayFields]
coordinates = true
direction = true
biome = true
dayAndTime = true
weather = true
moonPhase = true
season = true
lastDeathLocation = true