#Whether to log data regarding the location and data stored when placing cobblemon trial spawners.
enableDebugLogs = false
#Whether to do any spawner replacement at all. If set to false, this will disable all spawner replacement.
replaceGeneratedSpawnersWithCobblemonSpawners = true
#Whether to do any spawner replacement in structures. If set to false, this will disable all spawner replacement in structures.
replaceSpawnersInStructuresWithCobblemonSpawners = true
#Whether to do any spawner replacement in Features. If set to false, this will disable the spawner replacement for any spawners in features (eg. Monster_Rooms)
replaceSpawnersInFeaturesWithCobblemonSpawners = true
#Whether to replace any spawners that are not listed in configuration with a default spawner. If set to false, this will leave spawners that do not have custom spawn data created.
replaceAnyUnspecifiedSpawnersWithDefaultCobblemonSpawners = true
#This allows Spawned Pokemon to be Catchable. If set to True, regardless of spawner settings, Pokemon will always be catchable.If set to false whether Spawned Pokemon can be catchable or not is left up to the Spawner's Settings.NOTE: This will only apply to newly created spawners.
spawnedPokemonAreUncatchable = true
#This allows Spawned Pokemon to be defeated outside of battle. If set to true, regardless of spawner settings, Pokemon will be required to be defeated in battle.If set to false whether Spawned Pokemon can be defeated in battle or not is left up to the Spawner's Settings.NOTE: This will only apply to newly created spawners.
spawnedPokemonMustBeDefeatedInBattle = true
#This allows Spawned Pokemon to be Aggressive and attack players when spawned.If set to true whether Spawned Pokemon can be aggressive or not is left up to the Pokemon's Settings.NOTE: This will only apply to newly created spawners.
allowSpawnedPokemonToBeAggressive = true
#This allows Percentage based control of mob spawner replacement.If set to true this will use the Mob Spawner Replacement Percentage to determine how often a mob spawner should be replaced.NOTE: This will only apply in newly generated chunks.
replaceMobSpawnersBasedOnPercentage = false
#This is what percentage (0.0 - 1.0) Mob Spawners will be replaced, eg: .75 will mean 75% of the mob spawners on average will be replaced.NOTE: This will only apply in newly generated chunks.
# Default: 0.0
# Range: 0.0 ~ 1.0
mobSpawnerReplacementPercentage = 0.0
#This allows Percentage based control of trial spawner replacement.If set to true this will use the Trial Spawner Replacement Percentage to determine how often a trial spawner should be replaced.NOTE: This will only apply in newly generated chunks.
replaceTrialSpawnersBasedOnPercentage = false
#This is what percentage (0.0 - 1.0) Trial Spawners will be replaced, eg: .75 will mean 75% of the trial spawners on average will be replaced.NOTE: This will only apply in newly generated chunks.
# Default: 0.0
# Range: 0.0 ~ 1.0
trialSpawnerReplacementPercentage = 0.0
