#General settings
[general]
	#Is Enabled? (Optional glyph from Adams Ars Plus, disabled by default).
	enabled = false
	#Cost
	# Default: 180
	# Range: > -2147483648
	cost = 180
	#Is Starter Glyph?
	starter = false
	#The maximum number of times this glyph may appear in a single spell
	# Default: 2147483647
	# Range: > 1
	per_spell_limit = 2147483647
	#The tier of the glyph
	# Default: 3
	# Range: 1 ~ 99
	glyph_tier = 3
