name = "Cobblemon: Ho-Oh's Chosen"
author = "robonebi"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8339f9d37ab29aef8d057c69c2cd02eaa0bc6d1dd336e880ba367791afd91ca8"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.219"

[options]
datapack-folder = "global_packs/required_data"
