name = "Cobblemon: Ho-Oh's Chosen"
author = "robonebi"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "48c76de0727dd876200079ae94752af2b43be723c04a175f846bc34a8a083b31"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.219"

[options]
datapack-folder = "global_packs/required_data"
