name = "Cobblemon: Ho-Oh's Chosen"
author = "robonebi"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9e47e11e13800def8ffa01b5071467785b25e3fa4f0f96e35062217b7256fab2"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.219"

[options]
datapack-folder = "global_packs/required_data"
