name = "Cobblemon: Ho-Oh's Chosen"
author = "robonebi"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "badb45800fa1d0b2303f21c8bf913f2cd85eb6a4d972326437a9378a55ac72b6"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.219"

[options]
datapack-folder = "global_packs/required_data"
